version: "3"
services:
  fast-api-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8080:8080
    